server.port=8099

spring.application.name=sharecrm-im-gateway
spring.thymeleaf.cache=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# qixin
qixin.api.enabled=true
